### ISSUE TITLE
Vercel deployment config

### ISSUE THREAD

**Issue by serjdev** [w3cj/express-api-starter-ts#7]
I'm struggling to config deployment on vercel starting from this template. 
https://vercel.com/guides/using-express-with-vercel

what the `vercel.json` file should look like in this case ?

**Comment by w3cj** [comment]
I made a video on how to do this: https://www.youtube.com/watch?v=B-T69_VP2Ls

**Comment by serjdev** [comment]
oh cool! thanks

**Comment by brokeboiflex** [comment]
Could you add it to readme at least?
